### ISSUE TITLE
Can not login,but use token can

### ISSUE THREAD

**Issue by squallcx** [Banandana/LineSharp#8]
Today,Can not login,but use token can
How did it happen?

**Comment by Banandana** [comment]
I'm not sure, I haven't worked on this project in quite some time. :/

**Comment by PhoenixICE** [comment]
Hopefully you can continue working on this project, just curious how do you get the token?

**Comment by Banandana** [comment]
I can't remember, I'll take a look at it in a bit and hopefully I'll 
have an answer for you. I've also been programming as a full time job, 
so it's hard gathering the motivation to continue working on a project 
on my off time, especially of this nature.

**Comment by PhoenixICE** [comment]
Hey no problems, I've figured out how to get the authtoken, you actually have to login once and after confirming with your phone's pincode it returns an authtoken to program that logged in (in this case LineSharp) - but obviously this requires me to login first...but I've found a library that still works with login, and got my authtoken from there -> https://github.com/NitroXenon/LineThrift, apparently this person has stopped dev, since your repo is better.

**Comment by Banandana** [comment]
This library and how it functions on the lower level is very temperamental. I'm also needing to reorganize it on an architectural scale.

**Comment by Banandana** [comment]
Fixed.

**Comment by PhoenixICE** [comment]
Legend thanks, I can confirm this fix has allowed the login with password to work, as stated in your commit token login still isn't work, hopefully that can be added in down the track.

**Comment by Banandana** [comment]
I'll have to take a look at that as well at some point. All the programs I've made using this library have asked explicitly for a username and password, but I'll have to check out the token based login to see if anything's changed there.
